services:
  proxy-server:
    build: ./proxy-server
    networks:
      - app_net
    env_file:
      - proxy-server.env
    links:
      - server
    depends_on:
      - server

  server:
    container_name: proxy-main-server
    build: ./server
    networks:
      - app_net
    env_file:
      - server.env
    links:
      - database
    depends_on:
      - database

  admin:
    build: 
      context: ./admin
      args:
        - REACT_APP_BASE_API_URL=http://localhost/api
    networks:
      - app_net

  database:
    networks:
      - app_net
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=proxy
      - POSTGRES_PASSWORD=root
    volumes:
      - proxy-db:/var/lib/postgresql/data

  gateway: 
    networks:
      - app_net
    build: .
    ports:
      - "80:80"
    depends_on:
      - admin
      - proxy-server
      - server


volumes:
  proxy-db:

networks:
  app_net:
    driver: bridge
